apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  labels:
    app: face-recognition-edge-gpu
  name: face-recognition-edge-gpu
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/target: "70" # change this for different concurrency
    spec:
      containers:
        - image: "" # build the image from the apps/ and add it here
      nodeSelector:
        gpu: "true"
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: face-recognition-edge-gpu
  namespace: default
  labels:
    serving.knative.dev/service: face-recognition-edge-gpu
spec:
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      serving.knative.dev/service: face-recognition-edge-gpu
  podMetricsEndpoints:
  - targetPort: 9091
