apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: jetson-metrics-exporter
  namespace: observability
spec:
  selector:
    matchLabels:
      name: jetson-metrics-exporter
  template:
    metadata:
      labels:
        name: jetson-metrics-exporter
    spec:
      nodeSelector:
        igpu: "true"
      containers:
      - name: jetson-metrics-exporter
        image: <image_name> # removed for peer-review
        securityContext:
          privileged: true  # Run the container in privileged mode
        volumeMounts:
        - name: tegrastats
          mountPath: /usr/bin
            #subPath: tegrastats
        ports:
        - name: metrics
          containerPort: 9300
          hostPort: 9300
      volumes:
      - name: tegrastats
        hostPath:
          path: /usr/bin #/tegrastats  # Path to tegrastats on the host

