apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  labels:
    app: face-recognition-hybrid-cloud
  name: face-recognition-hybrid-cloud
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/target: "70" # change this for different concurrency
    spec:
      containers:
        - image: "summitshrestha/face-recognition-eqv-hybrid-cloud" # build the image from the apps/ and add it here
          #nodeSelector:
          #role: worker
